# no defines in python :C
PLAYING = 1
MENU = 2
MENU_EXIT = 3

# submenus
MENU_RANK = 4
MENU_DIFFICULTY = 5

# difficulty sets, yes don't judge me
SET_EASY = 6
SET_NORMAL = 7
SET_HARD = 8

# army settings
ALIEN_SEPARATION_HORIZONTAL = 12
ALIEN_SEPARATION_VERTICAL = 24
ALIEN_PER_ROW = 11
ALIEN3_ROWS = 1
ALIEN2_ROWS = 2
ALIEN1_ROWS = 2
EMPTY_ROWS_AT_TOP = 1
STEP_DISTANCE = 3
SHOOT_TIMER = 3

# points
ALIEN1_POINTS = 10
ALIEN2_POINTS = 20
ALIEN3_POINTS = 30
POINT_MULT_TIMER = 1